name: CI/CD actions

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install SW tools
        run: |
          winget install --id=Kitware.CMake -e
          winget install --id=Ninja-build.Ninja -e
          winget install --id=MartinStorsjo.LLVM-MinGW.UCRT -e
          winget install --id=Cppcheck.Cppcheck -e

      - name: Test CMake
        run: cmake --version

      - name: Test Ninja
        run: ninja --version

      - name: Test clang
        run: |
         clang++ --version
         clang-format --version
         clang-tidy --version

      - name: Test cppcheck
        run: cppcheck --version
