name: CI/CD actions

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-2025
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - name: Test CMake
        run: cmake --version

      - name: Test Ninja
        run: ninja --version

      - name: Test clang
        run: |
         clang++ --version
         clang-format --version
         clang-tidy --version

      - name: Test cppcheck
        run: cppcheck --version

      - name: Test g++
        run: g++ --version

      - name: Test python
        run: python --version

      - name: Test winget
        run: winget install --id=Ninja-build.Ninja -e
